export const data = [
    {
        id: '0',
        imagePath: '0.webp',
        width: 256,
        height: 142,
    },
    {
        id: '1',
        imagePath: '1.webp',
        width: 256,
        height: 142,
    },
    {
        id: '2',
        imagePath: '2.webp',
        width: 256,
        height: 77,
    },
    {
        id: '3',
        imagePath: '3.webp',
        width: 256,
        height: 59,
    },
    {
        id: '4',
        imagePath: '4.webp',
        width: 256,
        height: 54,
    },
    {
        id: '5',
        imagePath: '5.webp',
        width: 256,
        height: 169,
    },
    {
        id: '6',
        imagePath: '6.webp',
        width: 256,
        height: 91,
    },
    {
        id: '7',
        imagePath: '7.webp',
        width: 254,
        height: 47,
    },
    {
        id: '8',
        imagePath: '8.webp',
        width: 256,
        height: 252,
    },
    {
        id: '9',
        imagePath: '9.webp',
        width: 256,
        height: 49,
    },
    {
        id: '10',
        imagePath: '10.webp',
        width: 256,
        height: 73,
    },
    {
        id: '11',
        imagePath: '11.webp',
        width: 248,
        height: 162,
    },
    {
        id: '12',
        imagePath: '12.webp',
        width: 256,
        height: 89,
    },
    {
        id: '13',
        imagePath: '13.webp',
        width: 256,
        height: 256,
    },
    {
        id: '14',
        imagePath: '14.webp',
        width: 256,
        height: 83,
    },
    {
        id: '15',
        imagePath: '15.webp',
        width: 230,
        height: 52,
    },
    {
        id: '16',
        imagePath: '16.png',
        width: 220,
        height: 80,
    },
    {
        id: '17',
        imagePath: '17.webp',
        width: 253,
        height: 230,
    },
    {
        id: '18',
        imagePath: '18.webp',
        width: 238,
        height: 41,
    },
    {
        id: '19',
        imagePath: '19.webp',
        width: 214,
        height: 42,
    },
    {
        id: '20',
        imagePath: '20.png',
        width: 256,
        height: 80,
    },
    {
        id: '21',
        imagePath: '21.webp',
        width: 212,
        height: 153,
    },
    {
        id: '22',
        imagePath: '22.webp',
        width: 244,
        height: 52,
    },
    {
        id: '23',
        imagePath: '23.webp',
        width: 256,
        height: 65,
    },
]
