export const europeanCountriesDDI = [
  { country: "Albânia", ddi: "+355", code: "AL" },
  { country: "Alemanha", ddi: "+49", code: "DE" },
  { country: "Andorra", ddi: "+376", code: "AD" },
  { country: "Armênia", ddi: "+374", code: "AM" },
  { country: "Áustria", ddi: "+43", code: "AT" },
  { country: "Azerbaijão", ddi: "+994", code: "AZ" },
  { country: "Bélgica", ddi: "+32", code: "BE" },
  { country: "Brazil", ddi: "+55", code: "BR" },
  { country: "Bielorrússia", ddi: "+375", code: "BY" },
  { country: "Bósnia e Herzegovina", ddi: "+387", code: "BA" },
  { country: "Bulgária", ddi: "+359", code: "BG" },
  { country: "Chipre", ddi: "+357", code: "CY" },
  { country: "Croácia", ddi: "+385", code: "HR" },
  { country: "Dinamarca", ddi: "+45", code: "DK" },
  { country: "Eslováquia", ddi: "+421", code: "SK" },
  { country: "Eslovênia", ddi: "+386", code: "SI" },
  { country: "Espanha", ddi: "+34", code: "ES" },
  { country: "Estônia", ddi: "+372", code: "EE" },
  { country: "Finlândia", ddi: "+358", code: "FI" },
  { country: "França", ddi: "+33", code: "FR" },
  { country: "Geórgia", ddi: "+995", code: "GE" },
  { country: "Grécia", ddi: "+30", code: "GR" },
  { country: "Hungria", ddi: "+36", code: "HU" },
  { country: "Irlanda", ddi: "+353", code: "IE" },
  { country: "Islândia", ddi: "+354", code: "IS" },
  { country: "Itália", ddi: "+39", code: "IT" },
  { country: "Letônia", ddi: "+371", code: "LV" },
  { country: "Liechtenstein", ddi: "+423", code: "LI" },
  { country: "Lituânia", ddi: "+370", code: "LT" },
  { country: "Luxemburgo", ddi: "+352", code: "LU" },
  { country: "Macedônia do Norte", ddi: "+389", code: "MK" },
  { country: "Malta", ddi: "+356", code: "MT" },
  { country: "Moldávia", ddi: "+373", code: "MD" },
  { country: "Mônaco", ddi: "+377", code: "MC" },
  { country: "Montenegro", ddi: "+382", code: "ME" },
  { country: "Noruega", ddi: "+47", code: "NO" },
  { country: "Países Baixos", ddi: "+31", code: "NL" },
  { country: "Polônia", ddi: "+48", code: "PL" },
  { country: "Portugal", ddi: "+351", code: "PT" },
  { country: "Reino Unido", ddi: "+44", code: "GB" },
  { country: "República Tcheca", ddi: "+420", code: "CZ" },
  { country: "Romênia", ddi: "+40", code: "RO" },
  { country: "Rússia", ddi: "+7", code: "RU" },
  { country: "San Marino", ddi: "+378", code: "SM" },
  { country: "Sérvia", ddi: "+381", code: "RS" },
  { country: "Suécia", ddi: "+46", code: "SE" },
  { country: "Suíça", ddi: "+41", code: "CH" },
  { country: "Turquia", ddi: "+90", code: "TR" },
  { country: "Ucrânia", ddi: "+380", code: "UA" },
  { country: "Vaticano", ddi: "+39", code: "VA" }
];
