export const europeanCountriesDDI = [
    { country: "Albânia", ddi: "+355" },
    { country: "Alemanha", ddi: "+49" },
    { country: "Andorra", ddi: "+376" },
    { country: "Armênia", ddi: "+374" },
    { country: "Áustria", ddi: "+43" },
    { country: "Azerbaijão", ddi: "+994" },
    { country: "Bélgica", ddi: "+32" },
    { country: "Brazil", ddi: "+55" },
    { country: "Bielorrússia", ddi: "+375" },
    { country: "Bósnia e Herzegovina", ddi: "+387" },
    { country: "Bulgária", ddi: "+359" },
    { country: "Chipre", ddi: "+357" },
    { country: "Croácia", ddi: "+385" },
    { country: "Dinamarca", ddi: "+45" },
    { country: "Eslováquia", ddi: "+421" },
    { country: "Eslovênia", ddi: "+386" },
    { country: "Espanha", ddi: "+34" },
    { country: "Estônia", ddi: "+372" },
    { country: "Finlândia", ddi: "+358" },
    { country: "França", ddi: "+33" },
    { country: "Geórgia", ddi: "+995" },
    { country: "Grécia", ddi: "+30" },
    { country: "Hungria", ddi: "+36" },
    { country: "Irlanda", ddi: "+353" },
    { country: "Islândia", ddi: "+354" },
    { country: "Itália", ddi: "+39" },
    { country: "Letônia", ddi: "+371" },
    { country: "Liechtenstein", ddi: "+423" },
    { country: "Lituânia", ddi: "+370" },
    { country: "Luxemburgo", ddi: "+352" },
    { country: "Macedônia do Norte", ddi: "+389" },
    { country: "Malta", ddi: "+356" },
    { country: "Moldávia", ddi: "+373" },
    { country: "Mônaco", ddi: "+377" },
    { country: "Montenegro", ddi: "+382" },
    { country: "Noruega", ddi: "+47" },
    { country: "Países Baixos", ddi: "+31" },
    { country: "Polônia", ddi: "+48" },
    { country: "Portugal", ddi: "+351" },
    { country: "Reino Unido", ddi: "+44" },
    { country: "República Tcheca", ddi: "+420" },
    { country: "Romênia", ddi: "+40" },
    { country: "Rússia", ddi: "+7" },
    { country: "San Marino", ddi: "+378" },
    { country: "Sérvia", ddi: "+381" },
    { country: "Suécia", ddi: "+46" },
    { country: "Suíça", ddi: "+41" },
    { country: "Turquia", ddi: "+90" },
    { country: "Ucrânia", ddi: "+380" },
    { country: "Vaticano", ddi: "+39" }
  ];
  